version: '3'


services:
  web:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173


  backend:
    build:
        context: ./Backend
        dockerfile: Dockerfile
    ports:
      - 3000:3000